### ISSUE TITLE
Duplicate Return.

### ISSUE THREAD

**Issue by m-negahi** [baghayi/skyroom#3]
https://github.com/baghayi/skyroom/blob/b12482f5de5513f698322227f6e0fd3702c78ff9/src/Room.php#L40

**Comment by baghayi** [comment]
عه آره. 
احتمالا واسه احتیاط بیشتر گذاشتم :)))

پول ریکوئست نمی فرستین واسش؟

**Comment by m-negahi** [comment]
من هنوز وارد کد نویسی نشدم ، انشالله پروژم رو استارت بزنم حتمی با اجازتون.

**Comment by baghayi** [comment]
این حل شد.
